import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    backgroundColor: "#120b1e",
    flex: 1,
  },
  header: {
    alignItems: "center",
    borderBottomColor: "#2a1d3e",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  appName: {
    color: "#f4efff",
    fontSize: 22,
    fontWeight: "800",
  },
  subtitle: {
    color: "#8b7aa7",
    fontSize: 12,
    marginTop: 2,
  },
  statusPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  statusLive: {
    backgroundColor: "#1f6f5b",
  },
  statusOff: {
    backgroundColor: "#3a284e",
  },
  statusText: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "800",
  },
  controls: {
    gap: 10,
    paddingHorizontal: 12,
    paddingTop: 12,
    zIndex: 2,
  },
  notice: {
    backgroundColor: "#2a1d3e",
    borderColor: "#4b334f",
    borderRadius: 8,
    borderWidth: 1,
    marginHorizontal: 12,
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  noticeText: {
    color: "#ff737f",
    fontSize: 13,
    fontWeight: "900",
    textAlign: "center",
  },
  marketTabs: {
    backgroundColor: "#1b102c",
    borderColor: "#2b1c43",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    padding: 5,
  },
  marketTab: {
    alignItems: "center",
    borderRadius: 6,
    flex: 1,
    paddingVertical: 9,
  },
  marketTabActive: {
    backgroundColor: "#3b2a59",
  },
  marketTabDisabled: {
    opacity: 0.35,
  },
  marketText: {
    color: "#9b8db4",
    fontSize: 13,
    fontWeight: "800",
  },
  marketTextActive: {
    color: "#ffffff",
  },
  marketTextDisabled: {
    color: "#625571",
  },
  selectorRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
    zIndex: 3,
  },
  symbolSelector: {
    flex: 1,
    zIndex: 4,
  },
  dropdownButton: {
    alignItems: "center",
    backgroundColor: "#1b102c",
    borderColor: "#2b1c43",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 48,
    paddingHorizontal: 14,
  },
  dropdownLabel: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
  },
  dropdownChevron: {
    color: "#66d5c6",
    fontSize: 12,
    fontWeight: "900",
  },
  dropdownMenu: {
    backgroundColor: "#1b102c",
    borderColor: "#382652",
    borderRadius: 8,
    borderWidth: 1,
    left: 0,
    marginTop: 6,
    overflow: "hidden",
    position: "absolute",
    right: 0,
    top: 48,
    zIndex: 5,
  },
  symbolSearch: {
    borderBottomColor: "#2b1c43",
    borderBottomWidth: 1,
    color: "#ffffff",
    fontSize: 14,
    minHeight: 42,
    paddingHorizontal: 12,
  },
  symbolList: {
    maxHeight: 230,
  },
  symbolOption: {
    borderBottomColor: "#241733",
    borderBottomWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  symbolOptionActive: {
    backgroundColor: "#2c2141",
  },
  symbolOptionText: {
    color: "#d7cfea",
    fontSize: 14,
    fontWeight: "800",
  },
  symbolOptionTextActive: {
    color: "#66d5c6",
  },
  rangeInputWrap: {
    width: 112,
  },
  inputLabel: {
    color: "#75688c",
    fontSize: 11,
    fontWeight: "800",
    marginBottom: 4,
  },
  rangeInput: {
    backgroundColor: "#1b102c",
    borderColor: "#2b1c43",
    borderRadius: 8,
    borderWidth: 1,
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
    minHeight: 48,
    paddingHorizontal: 12,
    textAlign: "center",
  },
  applyButton: {
    alignItems: "center",
    backgroundColor: "#2f2445",
    borderColor: "#40305e",
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: "center",
    marginTop: 6,
    minHeight: 34,
  },
  applyButtonText: {
    color: "#66d5c6",
    fontSize: 12,
    fontWeight: "900",
  },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    zIndex: 1,
  },
  metaText: {
    color: "#75688c",
    fontSize: 12,
    fontWeight: "700",
  },
  columns: {
    borderBottomColor: "#2a1d3e",
    borderBottomWidth: 1,
    borderTopColor: "#2a1d3e",
    borderTopWidth: 1,
    flexDirection: "row",
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  columnText: {
    color: "#75688c",
    flex: 1,
    fontSize: 12,
    fontWeight: "800",
    textAlign: "right",
  },
  priceColumn: {
    textAlign: "left",
  },
  totalColumn: {
    paddingRight: 6,
  },
  book: {
    paddingBottom: 18,
  },
  row: {
    flexDirection: "row",
    height: 28,
    overflow: "hidden",
    paddingHorizontal: 14,
    position: "relative",
  },
  depthBar: {
    borderRadius: 5,
    bottom: 2,
    position: "absolute",
    right: 8,
    top: 2,
  },
  askDepth: {
    backgroundColor: "rgba(238, 91, 104, 0.32)",
  },
  bidDepth: {
    backgroundColor: "rgba(74, 190, 174, 0.34)",
  },
  rowText: {
    color: "#d7cfea",
    flex: 1,
    fontSize: 13,
    fontVariant: ["tabular-nums"],
    lineHeight: 28,
    textAlign: "right",
  },
  askText: {
    color: "#ff737f",
  },
  bidText: {
    color: "#62d0c0",
  },
  spreadRow: {
    alignItems: "center",
    backgroundColor: "#170f25",
    borderBottomColor: "#2a1d3e",
    borderBottomWidth: 1,
    borderTopColor: "#2a1d3e",
    borderTopWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    height: 52,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  spreadPrice: {
    color: "#f4efff",
    fontSize: 20,
    fontWeight: "900",
  },
  spreadText: {
    color: "#8b7aa7",
    fontSize: 12,
    fontWeight: "700",
  },
  ratioContent: {
    paddingBottom: 24,
  },
  ratioSection: {
    borderBottomColor: "#2a1d3e",
    borderBottomWidth: 1,
    paddingHorizontal: 16,
    paddingVertical: 18,
  },
  ratioHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  ratioTitle: {
    color: "#f4efff",
    fontSize: 16,
    fontWeight: "900",
  },
  ratioSubtitle: {
    color: "#8b7aa7",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 6,
  },
  shareGlyph: {
    color: "#8b7aa7",
    fontSize: 20,
    fontWeight: "900",
  },
  chart: {
    height: 170,
    paddingLeft: 48,
    paddingRight: 40,
    position: "relative",
  },
  chartBars: {
    alignItems: "flex-end",
    flexDirection: "row",
    gap: 2,
    height: 140,
    justifyContent: "center",
  },
  emptyChart: {
    alignItems: "center",
    height: 140,
    justifyContent: "center",
  },
  emptyChartText: {
    color: "#75688c",
    fontSize: 13,
    fontWeight: "800",
  },
  ratioColumn: {
    flexDirection: "column",
    height: 140,
    justifyContent: "flex-end",
    position: "relative",
    flex: 1,
  },
  shortRatioBar: {
    backgroundColor: "#ff3f63",
    borderTopLeftRadius: 3,
    borderTopRightRadius: 3,
    width: "100%",
  },
  longRatioBar: {
    backgroundColor: "#19d184",
    borderBottomLeftRadius: 3,
    borderBottomRightRadius: 3,
    width: "100%",
  },
  ratioLineDot: {
    backgroundColor: "#ffffff",
    borderRadius: 3,
    height: 5,
    left: 1,
    position: "absolute",
    width: 5,
    zIndex: 2,
  },
  gridLineTop: {
    backgroundColor: "#2a1d3e",
    height: 1,
    left: 48,
    position: "absolute",
    right: 0,
    top: 0,
  },
  gridLineMid: {
    backgroundColor: "#2a1d3e",
    height: 1,
    left: 48,
    position: "absolute",
    right: 0,
    top: 70,
  },
  gridLineBottom: {
    backgroundColor: "#2a1d3e",
    height: 1,
    left: 48,
    position: "absolute",
    right: 0,
    top: 140,
  },
  axisLabel: {
    color: "#8b7aa7",
    fontSize: 12,
    fontVariant: ["tabular-nums"],
    position: "absolute",
    left: 0,
    width: 42,
  },
  axisTop: {
    top: -7,
  },
  axisMiddle: {
    top: 63,
  },
  axisBottom: {
    top: 133,
  },
  legendRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 20,
    justifyContent: "center",
    marginTop: 8,
  },
  legendItem: {
    alignItems: "center",
    flexDirection: "row",
    gap: 7,
  },
  legendItemCenter: {
    alignItems: "center",
    flexDirection: "row",
    gap: 7,
    justifyContent: "center",
    marginTop: 12,
  },
  legendDot: {
    borderRadius: 3,
    height: 10,
    width: 10,
  },
  shortLegend: {
    backgroundColor: "#ff3f63",
  },
  longLegend: {
    backgroundColor: "#19d184",
  },
  ratioLineSample: {
    backgroundColor: "#ffffff",
    height: 2,
    width: 16,
  },
  legendText: {
    color: "#9b8db4",
    fontSize: 12,
    fontWeight: "700",
  },
  ratioSummary: {
    backgroundColor: "#1b102c",
    borderColor: "#2b1c43",
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    margin: 16,
    padding: 14,
  },
  summaryLabel: {
    color: "#75688c",
    fontSize: 11,
    fontWeight: "800",
    marginBottom: 6,
  },
  summaryLong: {
    color: "#19d184",
    fontSize: 17,
    fontWeight: "900",
  },
  summaryShort: {
    color: "#ff3f63",
    fontSize: 17,
    fontWeight: "900",
  },
  summaryValue: {
    color: "#f4efff",
    fontSize: 17,
    fontWeight: "900",
  },
});
